package com.duan.dormitorysystem.dao;

import com.duan.dormitorysystem.bean.Building;
import com.duan.dormitorysystem.bean.BuildingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuildingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    long countByExample(BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    int deleteByExample(BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    int deleteByPrimaryKey(Long dormId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    int insert(Building record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    int insertSelective(Building record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    List<Building> selectByExample(BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    Building selectByPrimaryKey(Long dormId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Building record, @Param("example") BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    int updateByExample(@Param("record") Building record, @Param("example") BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    int updateByPrimaryKeySelective(Building record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    int updateByPrimaryKey(Building record);
}