package com.duan.dormitorysystem.dao;

import com.duan.dormitorysystem.bean.Manager;
import com.duan.dormitorysystem.bean.ManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    long countByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    int deleteByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    int deleteByPrimaryKey(Long manaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    List<Manager> selectByExample(ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    Manager selectByPrimaryKey(Long manaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") Manager record, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    int updateByExample(@Param("record") Manager record, @Param("example") ManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    int updateByPrimaryKey(Manager record);
}