package com.duan.dormitorysystem.dao;

import com.duan.dormitorysystem.bean.StuRelationBul;
import com.duan.dormitorysystem.bean.StuRelationBulExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StuRelationBulMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    long countByExample(StuRelationBulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int deleteByExample(StuRelationBulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int deleteByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int insert(StuRelationBul record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int insertSelective(StuRelationBul record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    List<StuRelationBul> selectByExample(StuRelationBulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    StuRelationBul selectByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") StuRelationBul record, @Param("example") StuRelationBulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int updateByExample(@Param("record") StuRelationBul record, @Param("example") StuRelationBulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int updateByPrimaryKeySelective(StuRelationBul record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int updateByPrimaryKey(StuRelationBul record);
}