package com.duan.dormitorysystem.dao;

import com.duan.dormitorysystem.bean.StuRelationInter;
import com.duan.dormitorysystem.bean.StuRelationInterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StuRelationInterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    long countByExample(StuRelationInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int deleteByExample(StuRelationInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int deleteByPrimaryKey(Long interId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int insert(StuRelationInter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int insertSelective(StuRelationInter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    List<StuRelationInter> selectByExample(StuRelationInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    StuRelationInter selectByPrimaryKey(Long interId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") StuRelationInter record, @Param("example") StuRelationInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int updateByExample(@Param("record") StuRelationInter record, @Param("example") StuRelationInterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int updateByPrimaryKeySelective(StuRelationInter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    int updateByPrimaryKey(StuRelationInter record);
}