package com.duan.dormitorysystem.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ManagerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public ManagerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andManaIdIsNull() {
            addCriterion("mana_id is null");
            return (Criteria) this;
        }

        public Criteria andManaIdIsNotNull() {
            addCriterion("mana_id is not null");
            return (Criteria) this;
        }

        public Criteria andManaIdEqualTo(Long value) {
            addCriterion("mana_id =", value, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaIdNotEqualTo(Long value) {
            addCriterion("mana_id <>", value, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaIdGreaterThan(Long value) {
            addCriterion("mana_id >", value, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("mana_id >=", value, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaIdLessThan(Long value) {
            addCriterion("mana_id <", value, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaIdLessThanOrEqualTo(Long value) {
            addCriterion("mana_id <=", value, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaIdIn(List<Long> values) {
            addCriterion("mana_id in", values, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaIdNotIn(List<Long> values) {
            addCriterion("mana_id not in", values, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaIdBetween(Long value1, Long value2) {
            addCriterion("mana_id between", value1, value2, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaIdNotBetween(Long value1, Long value2) {
            addCriterion("mana_id not between", value1, value2, "manaId");
            return (Criteria) this;
        }

        public Criteria andManaNameIsNull() {
            addCriterion("mana_name is null");
            return (Criteria) this;
        }

        public Criteria andManaNameIsNotNull() {
            addCriterion("mana_name is not null");
            return (Criteria) this;
        }

        public Criteria andManaNameEqualTo(String value) {
            addCriterion("mana_name =", value, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameNotEqualTo(String value) {
            addCriterion("mana_name <>", value, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameGreaterThan(String value) {
            addCriterion("mana_name >", value, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameGreaterThanOrEqualTo(String value) {
            addCriterion("mana_name >=", value, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameLessThan(String value) {
            addCriterion("mana_name <", value, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameLessThanOrEqualTo(String value) {
            addCriterion("mana_name <=", value, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameLike(String value) {
            addCriterion("mana_name like", value, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameNotLike(String value) {
            addCriterion("mana_name not like", value, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameIn(List<String> values) {
            addCriterion("mana_name in", values, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameNotIn(List<String> values) {
            addCriterion("mana_name not in", values, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameBetween(String value1, String value2) {
            addCriterion("mana_name between", value1, value2, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaNameNotBetween(String value1, String value2) {
            addCriterion("mana_name not between", value1, value2, "manaName");
            return (Criteria) this;
        }

        public Criteria andManaPasswordIsNull() {
            addCriterion("mana_password is null");
            return (Criteria) this;
        }

        public Criteria andManaPasswordIsNotNull() {
            addCriterion("mana_password is not null");
            return (Criteria) this;
        }

        public Criteria andManaPasswordEqualTo(String value) {
            addCriterion("mana_password =", value, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordNotEqualTo(String value) {
            addCriterion("mana_password <>", value, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordGreaterThan(String value) {
            addCriterion("mana_password >", value, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("mana_password >=", value, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordLessThan(String value) {
            addCriterion("mana_password <", value, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordLessThanOrEqualTo(String value) {
            addCriterion("mana_password <=", value, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordLike(String value) {
            addCriterion("mana_password like", value, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordNotLike(String value) {
            addCriterion("mana_password not like", value, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordIn(List<String> values) {
            addCriterion("mana_password in", values, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordNotIn(List<String> values) {
            addCriterion("mana_password not in", values, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordBetween(String value1, String value2) {
            addCriterion("mana_password between", value1, value2, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaPasswordNotBetween(String value1, String value2) {
            addCriterion("mana_password not between", value1, value2, "manaPassword");
            return (Criteria) this;
        }

        public Criteria andManaEmailIsNull() {
            addCriterion("mana_email is null");
            return (Criteria) this;
        }

        public Criteria andManaEmailIsNotNull() {
            addCriterion("mana_email is not null");
            return (Criteria) this;
        }

        public Criteria andManaEmailEqualTo(String value) {
            addCriterion("mana_email =", value, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailNotEqualTo(String value) {
            addCriterion("mana_email <>", value, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailGreaterThan(String value) {
            addCriterion("mana_email >", value, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailGreaterThanOrEqualTo(String value) {
            addCriterion("mana_email >=", value, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailLessThan(String value) {
            addCriterion("mana_email <", value, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailLessThanOrEqualTo(String value) {
            addCriterion("mana_email <=", value, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailLike(String value) {
            addCriterion("mana_email like", value, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailNotLike(String value) {
            addCriterion("mana_email not like", value, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailIn(List<String> values) {
            addCriterion("mana_email in", values, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailNotIn(List<String> values) {
            addCriterion("mana_email not in", values, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailBetween(String value1, String value2) {
            addCriterion("mana_email between", value1, value2, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andManaEmailNotBetween(String value1, String value2) {
            addCriterion("mana_email not between", value1, value2, "manaEmail");
            return (Criteria) this;
        }

        public Criteria andGmtCreatIsNull() {
            addCriterion("gmt_creat is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatIsNotNull() {
            addCriterion("gmt_creat is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatEqualTo(Date value) {
            addCriterion("gmt_creat =", value, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtCreatNotEqualTo(Date value) {
            addCriterion("gmt_creat <>", value, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtCreatGreaterThan(Date value) {
            addCriterion("gmt_creat >", value, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtCreatGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_creat >=", value, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtCreatLessThan(Date value) {
            addCriterion("gmt_creat <", value, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtCreatLessThanOrEqualTo(Date value) {
            addCriterion("gmt_creat <=", value, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtCreatIn(List<Date> values) {
            addCriterion("gmt_creat in", values, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtCreatNotIn(List<Date> values) {
            addCriterion("gmt_creat not in", values, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtCreatBetween(Date value1, Date value2) {
            addCriterion("gmt_creat between", value1, value2, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtCreatNotBetween(Date value1, Date value2) {
            addCriterion("gmt_creat not between", value1, value2, "gmtCreat");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_manager
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 05 11:44:27 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_manager
     *
     * @mbg.generated Sun Aug 05 11:44:27 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}