package com.duan.dormitorysystem.bean;

import java.util.Date;

public class ManaRelationStu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mana_stu.relation_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private Long relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mana_stu.mana_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private Long manaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mana_stu.stu_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private Long stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mana_stu.gmt_creat
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private Date gmtCreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mana_stu.gmt_modified
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mana_stu
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public ManaRelationStu(Long relationId, Long manaId, Long stuId, Date gmtCreat, Date gmtModified) {
        this.relationId = relationId;
        this.manaId = manaId;
        this.stuId = stuId;
        this.gmtCreat = gmtCreat;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mana_stu
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public ManaRelationStu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mana_stu.relation_id
     *
     * @return the value of mana_stu.relation_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mana_stu.relation_id
     *
     * @param relationId the value for mana_stu.relation_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mana_stu.mana_id
     *
     * @return the value of mana_stu.mana_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public Long getManaId() {
        return manaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mana_stu.mana_id
     *
     * @param manaId the value for mana_stu.mana_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setManaId(Long manaId) {
        this.manaId = manaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mana_stu.stu_id
     *
     * @return the value of mana_stu.stu_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mana_stu.stu_id
     *
     * @param stuId the value for mana_stu.stu_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mana_stu.gmt_creat
     *
     * @return the value of mana_stu.gmt_creat
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public Date getGmtCreat() {
        return gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mana_stu.gmt_creat
     *
     * @param gmtCreat the value for mana_stu.gmt_creat
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setGmtCreat(Date gmtCreat) {
        this.gmtCreat = gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mana_stu.gmt_modified
     *
     * @return the value of mana_stu.gmt_modified
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mana_stu.gmt_modified
     *
     * @param gmtModified the value for mana_stu.gmt_modified
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}