package com.duan.dormitorysystem.bean;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stu.stu_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private Long stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stu.stu_card_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private String stuCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stu.stu_name
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stu.stu_password
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private String stuPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stu.stu_email
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private String stuEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stu.gmt_create
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stu.gmt_modified
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stu
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Student(Long stuId, String stuCardId, String stuName, String stuPassword, String stuEmail, Date gmtCreate, Date gmtModified) {
        this.stuId = stuId;
        this.stuCardId = stuCardId;
        this.stuName = stuName;
        this.stuPassword = stuPassword;
        this.stuEmail = stuEmail;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stu
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Student() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stu.stu_id
     *
     * @return the value of tbl_stu.stu_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stu.stu_id
     *
     * @param stuId the value for tbl_stu.stu_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stu.stu_card_id
     *
     * @return the value of tbl_stu.stu_card_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public String getStuCardId() {
        return stuCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stu.stu_card_id
     *
     * @param stuCardId the value for tbl_stu.stu_card_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setStuCardId(String stuCardId) {
        this.stuCardId = stuCardId == null ? null : stuCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stu.stu_name
     *
     * @return the value of tbl_stu.stu_name
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stu.stu_name
     *
     * @param stuName the value for tbl_stu.stu_name
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stu.stu_password
     *
     * @return the value of tbl_stu.stu_password
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public String getStuPassword() {
        return stuPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stu.stu_password
     *
     * @param stuPassword the value for tbl_stu.stu_password
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setStuPassword(String stuPassword) {
        this.stuPassword = stuPassword == null ? null : stuPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stu.stu_email
     *
     * @return the value of tbl_stu.stu_email
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public String getStuEmail() {
        return stuEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stu.stu_email
     *
     * @param stuEmail the value for tbl_stu.stu_email
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setStuEmail(String stuEmail) {
        this.stuEmail = stuEmail == null ? null : stuEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stu.gmt_create
     *
     * @return the value of tbl_stu.gmt_create
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stu.gmt_create
     *
     * @param gmtCreate the value for tbl_stu.gmt_create
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stu.gmt_modified
     *
     * @return the value of tbl_stu.gmt_modified
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stu.gmt_modified
     *
     * @param gmtModified the value for tbl_stu.gmt_modified
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}