package com.duan.dormitorysystem.bean;

import java.util.Date;

public class StuRelationBul {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_building.relation_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private Long relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_building.stu_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private Long stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_building.dorm_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private Long dormId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_building.bed_num
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private Byte bedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_building.gmt_create
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_building.gmt_modified
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public StuRelationBul(Long relationId, Long stuId, Long dormId, Byte bedNum, Date gmtCreate, Date gmtModified) {
        this.relationId = relationId;
        this.stuId = stuId;
        this.dormId = dormId;
        this.bedNum = bedNum;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_building
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public StuRelationBul() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_building.relation_id
     *
     * @return the value of stu_building.relation_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_building.relation_id
     *
     * @param relationId the value for stu_building.relation_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_building.stu_id
     *
     * @return the value of stu_building.stu_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_building.stu_id
     *
     * @param stuId the value for stu_building.stu_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_building.dorm_id
     *
     * @return the value of stu_building.dorm_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Long getDormId() {
        return dormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_building.dorm_id
     *
     * @param dormId the value for stu_building.dorm_id
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setDormId(Long dormId) {
        this.dormId = dormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_building.bed_num
     *
     * @return the value of stu_building.bed_num
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Byte getBedNum() {
        return bedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_building.bed_num
     *
     * @param bedNum the value for stu_building.bed_num
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setBedNum(Byte bedNum) {
        this.bedNum = bedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_building.gmt_create
     *
     * @return the value of stu_building.gmt_create
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_building.gmt_create
     *
     * @param gmtCreate the value for stu_building.gmt_create
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_building.gmt_modified
     *
     * @return the value of stu_building.gmt_modified
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_building.gmt_modified
     *
     * @param gmtModified the value for stu_building.gmt_modified
     *
     * @mbg.generated Fri Jun 29 08:47:09 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}