package com.duan.dormitorysystem.bean;

import java.util.Date;

public class StuRelationInter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_inter.inter_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private Long interId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_inter.stu_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private Long stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_inter.inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private String inter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_inter.gmt_creat
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private Date gmtCreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_inter.gmt_modified
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public StuRelationInter(Long interId, Long stuId, String inter, Date gmtCreat, Date gmtModified) {
        this.interId = interId;
        this.stuId = stuId;
        this.inter = inter;
        this.gmtCreat = gmtCreat;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public StuRelationInter() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_inter.inter_id
     *
     * @return the value of stu_inter.inter_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public Long getInterId() {
        return interId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_inter.inter_id
     *
     * @param interId the value for stu_inter.inter_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setInterId(Long interId) {
        this.interId = interId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_inter.stu_id
     *
     * @return the value of stu_inter.stu_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_inter.stu_id
     *
     * @param stuId the value for stu_inter.stu_id
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_inter.inter
     *
     * @return the value of stu_inter.inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public String getInter() {
        return inter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_inter.inter
     *
     * @param inter the value for stu_inter.inter
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setInter(String inter) {
        this.inter = inter == null ? null : inter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_inter.gmt_creat
     *
     * @return the value of stu_inter.gmt_creat
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public Date getGmtCreat() {
        return gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_inter.gmt_creat
     *
     * @param gmtCreat the value for stu_inter.gmt_creat
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setGmtCreat(Date gmtCreat) {
        this.gmtCreat = gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_inter.gmt_modified
     *
     * @return the value of stu_inter.gmt_modified
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_inter.gmt_modified
     *
     * @param gmtModified the value for stu_inter.gmt_modified
     *
     * @mbg.generated Wed Mar 06 11:18:37 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}